import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <link rel="stylesheet" href="/mainPageStyle/css/style.css" />
        <script defer src="/mainPageStyle/js/ie.js"></script>
      </body>
    </html>
  );
}
