import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import AuthContext from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <div className="antialiased dark:bg-gray-900 flex flex-col h-screen">
            <Navbar />
            <main className="container p-10 h-auto pt-20 grow">{children}</main>
            <Footer />
          </div>
        </AuthContext>
      </body>
    </html>
  );
}
